### ISSUE TITLE
MySQL Provisioning for vagrant up on allinone

### ISSUE THREAD

**Issue by alex4u2nv** [Alfresco/alfresco-spk#15]
```
==> default: Error executing action `grant` on resource 'mysql_database_user[alfresco]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: TypeError
==> default: ---------
==> default: Mysql is not a class
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef-solo/chef-solo-1/cookbooks/database/libraries/provider_database_mysql_user.rb:29:in `load_current_resource'
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-solo/chef-solo-1/cookbooks/alfresco/recipes/mysql_createdb.rb
==> default: 
==> default:  22:     mysql_database_user db_user do
==> default:  23:     connection          db_info
==> default:  24:     database_name       db_database
==> default:  25:     password            db_pass
==> default:  26:     privileges          [ :all ]
==> default:  27:     host                repo_host
==> default:  28:     action              :grant
==> default:  29:   end
==> default:  30: end
==> default: 
==> default: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-solo/chef-solo-1/cookbooks/alfresco/recipes/mysql_createdb.rb:22:in `block in from_file'
==> default: 
==> default: mysql_database_user("alfresco") do
==> default:   provider Chef::Provider::Database::MysqlUser
==> default:   action [:grant]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   database_name "alfresco"
==> default:   username "alfresco"
==> default:   host "%"
==> default:   privileges [:all]
==> default:   cookbook_name :alfresco
==> default:   recipe_name "mysql_createdb"
==> default:   connection {:host=>"alfresco-allinone", :port=>3306, :username=>"root", :password=>"ilikerandompasswords"}
==> default:   password "alfresco"
==> default: end
==> default: 
==> default: 
==> default: 
```

**Comment by maoo** [comment]
Hi @alex4u2nv , any update on this issue? Are you still experiencing the same issue? Thanks

**Comment by maoo** [comment]
Closing this issue, please reopen if you still can reproduce it
